name: Build and deploy Node.js app to Azure Web App - webapp--magnoli-node-crm

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"

      # NEW: Clean any previous build artifacts so nothing stale sneaks in
      - name: Clean dist
        run: rm -rf dist

      - name: Install, generate Prisma, migrate, build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
        run: |
          npm ci
          npx prisma generate
          npx prisma migrate deploy
          npm run build --if-present

      # NEW: Guardrail – fail if any alias-import remains in compiled JS
      - name: Verify output has no "@/..." imports
        run: |
          if grep -R "from '@/\|require('@/" dist; then
            echo "Build output still contains '@/...' imports. Fix your imports or tsconfig-paths."
            exit 1
          fi

      # Optional but recommended to shrink package size
      - name: Prune dev dependencies
        run: npm prune --omit=dev

      - name: Create deployment package (release.zip)
        run: |
          rm -f release.zip
          zip -r release.zip . \
            -x ".git/*" ".github/*" "tests/*" "coverage/*" "node_modules/.cache/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_99A4A2E39C2F47BBA91164E77D56CE07 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_63AA3DD1668B4D32A99A249856459D04 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_666FB64B659F4A8891DF30D10BCDF74D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "webapp--magnoli-node-crm"
          slot-name: "Production"
          package: "release.zip"
          # NEW: wipe the app files before deploying the new package
          clean: true
