name: Build and deploy Node.js app to Azure Web App - webapp-staging-magnoli-node-crm

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"

      # NEW: Clean any previous build artifacts so nothing stale sneaks in
      - name: Clean dist
        run: rm -rf dist

      - name: Install, generate Prisma, migrate, build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
        run: |
          npm ci
          npx prisma generate
          npx prisma migrate deploy
          npm run build --if-present

      # NEW: Guardrail – fail if any alias-import remains in compiled JS
      - name: Verify output has no "@/..." imports
        run: |
          if grep -R "from '@/\|require('@/" dist; then
            echo "Build output still contains '@/...' imports. Fix your imports or tsconfig-paths."
            exit 1
          fi

      # Optional but recommended to shrink package size
      - name: Prune dev dependencies
        run: npm prune --omit=dev

      - name: Create deployment package (release.zip)
        run: |
          rm -f release.zip
          zip -r release.zip . \
            -x ".git/*" ".github/*" "tests/*" "coverage/*" "node_modules/.cache/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0B4694D63959488597D722F26B32E7EC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_65DAA938C47D4793AB6F30D134B45CF5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EA42869260C749E29FB3C93CEA90CDE3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "webapp-staging-magnoli-node-crm"
          slot-name: "Production"
          package: "release.zip"
          # NEW: wipe the app files before deploying the new package
          clean: true
